#!/bin/bash

long_date=$(date '+%a, %b %d')
short_date=$(date '+%d-%m')
color="#93a1a1"
printf "<span foreground=\"%s\">%s</span>\n" $color "$long_date";
printf "<span foreground=\"%s\">%s</span>\n" $color "$short_date";
