#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2014 Andreas Guldstrand <andreas.guldstrand@gmail.com>
#
# Licensed under the terms of the GNU GPL v3, or any later version.

use Math::Round;
use strict;
use warnings;
use utf8;

my $t_warn = 60;
my $t_crit = 80;
my $cpu_usage = -1;
my $color;


# Get CPU usage
$ENV{LC_ALL}="en_US"; # if mpstat is not run under en_US locale, things may break, so make sure it is
open (MPSTAT, 'mpstat 1 1 |') or die;
while (<MPSTAT>) {
    if (/^.*\s+(\d+\.\d+)\s+$/) {
        $cpu_usage = 100 - $1; # 100% - %idle
        last;
    }
}
close(MPSTAT);

$cpu_usage eq -1 and die 'Can\'t find CPU information';
$cpu_usage = round($cpu_usage);

if ($cpu_usage >= $t_crit) {
    $color = "#dc322f";
} elsif ($cpu_usage >= $t_warn) {
    $color = "#b58900";
} else {
    $color = "#93a1a1";
}

printf "<span foreground=\"%s\">%d%%</span>\n", $color, $cpu_usage;
printf "<span foreground=\"%s\">%d%%</span>\n", $color, $cpu_usage;

exit 0;
