#!/bin/bash
[[ "$(hostname)" != "x1c" ]] && exit 1

color="#268bd2"

if [[ $(bluetoothctl show | grep "Powered: yes") ]]; then
    icon=""
    state="on"
else
    icon=""
    state="off"
fi

printf "<span foreground=\"%s\">%s %s</span>\n" $color "$icon" "$state";
