#!/bin/bash
set -uxe
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

echo "10de 2206" > /sys/bus/pci/drivers/vfio-pci/new_id
echo "0000:01:00.0" > /sys/bus/pci/devices/0000:01:00.0/driver/unbind
echo "0000:01:00.0" > /sys/bus/pci/drivers/vfio-pci/bind
echo "10de 2206" > /sys/bus/pci/drivers/vfio-pci/remove_id

echo "10de 1aef" > /sys/bus/pci/drivers/vfio-pci/new_id
echo "0000:01:00.1" > /sys/bus/pci/devices/0000:01:00.1/driver/unbind
echo "0000:01:00.1" > /sys/bus/pci/drivers/vfio-pci/bind
echo "10de 1aef" > /sys/bus/pci/drivers/vfio-pci/remove_id

# repeat for extra devices
rmmod nvidia_drm
rmmod nvidia_modeset
rmmod nvidia_uvm
rmmod nvidia
