#!/bin/bash
[[ $# != 1 ]] && exit 1
set -ue -o pipefail
lsf_host=$(bqueues -l $1 | grep HOSTS | awk '{print $2}' | sed 's/\/$//')
hosts=$(bhosts -X $lsf_host | grep ok | grep "^r" | awk '{print $1}' | tr '\n' ' ')
echo "#BSUB -m \"$hosts\""
