#!/bin/sh

LAUNCHER="rofi -dmenu -i -lines 20 -p"

USAGE="Usage: \
<span font_weight='bold'>Alt+o</span>: open-mode \
| <span font_weight='bold'>Alt+n</span>: add \
| <span font_weight='bold'>Alt+r</span>: remove-mode \
| <span font_weight='bold'>Alt+e</span>: edit"
KEYS="-kb-custom-1 Alt+o -kb-custom-2 Alt+n -kb-custom-3 Alt+r -kb-custom-4 Alt+e"

# Extract clipboard history from clipster and format for rofi
#  - Remove Newlines from clips
#  - Split into lines based on NUL byte
#  - Remove Leading whitespace
#  - Remove empty clipboard items
#  - Add line numbers to clip items
# NOTE: This is all done in a single line because bash can't store a NUL byte
function extract_selection()
{
    HIST="$(xcmenu --dmenu  | gawk '{printf("%3d  %s\n", NR, $0)}')"

    # Echo clipboard items to Rofi and save the selection made by user
    SELECTION="$(echo "$HIST" | $LAUNCHER $SEL_TXT: -mesg "$USAGE" $KEYS)"

    # Verify user made a selection
    if [ -n "$SELECTION" ]; then
        NUMBER="$(echo "$SELECTION" | cut -c1-3)"
        # xcmenu --get $(expr $NUMBER - 1) | tr -d '\n' | xcmenu --input --clipboard
        # TODO: fix \n at end of output
        xcmenu --get $(expr $NUMBER - 1) | xclip -sel clip
    fi
}

# main loop

retval=10 # show clipboard selection
while [ $retval -ne 0 ]
do
    case "$retval" in
        1)
            # rofi was closed (e.g. by ESC)
            exit 0
            ;;
        10)
            extract_selection
            retval=$?
            ;;
    esac
done
