#!/bin/sh

LAUNCHER="rofi -dmenu -i -lines 20 -p"
xcmenu --dmenu | $LAUNCHER "rofi-selection:"
exit 0

USAGE="Usage: \
<span font_weight='bold'>Alt+o</span>: open-mode \
| <span font_weight='bold'>Alt+n</span>: add \
| <span font_weight='bold'>Alt+r</span>: remove-mode \
| <span font_weight='bold'>Alt+e</span>: edit"
KEYS="-kb-custom-1 Alt+o -kb-custom-2 Alt+n -kb-custom-3 Alt+r -kb-custom-4 Alt+e"

# Extract clipboard history from clipster and format for rofi
#  - Remove Newlines from clips
#  - Split into lines based on NUL byte
#  - Remove Leading whitespace
#  - Remove empty clipboard items
#  - Add line numbers to clip items
# NOTE: This is all done in a single line because bash can't store a NUL byte
function extract_selection()
{
    if [ "$1" == "p" ]; then
        SEL_CMD="-p"
        SEL_TXT="primary"
    else
        SEL_CMD="-c"
        SEL_TXT="clipboard"
    fi
    C_HIST="$(clipster $SEL_CMD -o -n 0 -0 \
        | gawk 'BEGIN {RS = "\0"; FS="\n"; OFS=" " } { $1=$1; print $0 }'  \
        | sed 's/^ *//' \
        | sed '/^$/d' \
        | gawk '{printf("%3d  %s\n", NR, $0)}')"

    # Echo clipboard items to Rofi and save the selection made by user
    SELECTION="$(echo "$C_HIST" | $LAUNCHER $SEL_TXT: -mesg "$USAGE" $KEYS)"

    # Verify user made a selection
    if [ -n "$SELECTION" ]; then

        # Retrieve the line number from the beginning of selection
        NUMBER="$(echo "$SELECTION" | cut -c1-3)"
        # Extract clipboard history from clipster and find the nth non-empty clip based selected line number
        EXACT_SELECTION="$(clipster $SEL_CMD -o -n 0 -0 \
                   | gawk 'BEGIN {RS = "\0"; ORS = "\0"} NF > 0 { print }' \
                   | gawk 'BEGIN {RS = "\0"}'"NR == $NUMBER { print; exit }")"
        # Echo the selection back to clipster
        echo -n "$EXACT_SELECTION" | clipster $SEL_CMD
    fi
}

# main loop

retval=10 # show clipboard selection
while [ $retval -ne 0 ]
do
    case "$retval" in
        1)
            # rofi was closed (e.g. by ESC)
            exit 0
            ;;
        10)
            extract_selection
            retval=$?
            ;;
    esac
done
