#!/bin/bash

if [[ "$(hostname -s)" == "msi" ]]; then
    if [ $(uname -r | grep vfio -c) -eq 1 ]; then
	true
        # synergy&
    fi
fi

if [[ "$(hostname -s)" == "x1c" ]]; then
    nm-applet&
fi

# compton -c -b
# i3-subscribe
xcmenu -daemon
mpd
lxpolkit&
dunst&
firefox&
thunderbird&
termite -e ncmpcpp --name ncmpcpp&
i3-focus-last&
owncloud&
emacs --daemon
