#!/bin/bash

if [[ "$(hostname -s)" == "msi" ]] && [ "$XDG_VTNR" -eq 1]; then
    synergy&
    lxpolkit&
	thunderbird&
fi

if [ "$XDG_VTNR" -eq 1 ]; then
	qutebrowser&
	emacs --daemon
fi

if [ "$XDG_VTNR" -eq 2 ]; then
	steam-native
fi

# i3-subscribe
# xcmenu -daemon
nm-applet&
dunst&
i3-focus-last&
i3-scrachpad&
