#!/bin/bash
if [[ "$(hostname -s)" == "msi" ]]; then
    feh  --bg-fill '/home/llucido/Pictures/wallpapers/solarized/flower.jpg'
else
    feh  --bg-fill '/home/llucido/Pictures/wallpapers/solarized/flower.jpg'
fi
