#!/bin/bash

[ "$#" -ne 1 ] && exit -1;

function mpc_notify() {

    # send notification only when resuming
    if [ "$1" = toggle ]; then
       mpc status | grep "\[playing\]" || exit -1;
    fi

    song=$(mpc status -f "[[%artist% - ]&[%title%]]|[%file%]" | head -n 1)
    case "$1" in
        short) time="";;
        long|toggle) time=$(mpc status | sed -n 2p | cut -d " " -f5);;
        *) ;;
    esac
    notify-send -u low -t 2000 "$song" "$time"
}

case "$1" in
   prev) mpc --wait prev && mpc_notify short && i3b-send-signal 5;;
   next) mpc --wait next && mpc_notify short && i3b-send-signal 5;;
   toggle) mpc toggle --wait && mpc_notify toggle && i3b-send-signal 5;;
   status) mpc_notify long && i3b-send-signal 5;;
   stop) mpc stop && i3b-send-signal 5;;
   minus) mpc volume -5 && i3b-send-signal 5;;
   plus) mpc volume +5 && i3b-send-signal 5;;
   *) ;;
esac
